version: '3.1'

services:
  couchdb:
    image: couchdb:latest
    volumes:
      - $PWD/.couchdb/data:/opt/couchdb/data
      # - $PWD/.couchdb/etc:/opt/couchdb/etc
      # - $PWD/.couchdb/log:/opt/couchdb/log
    restart: always
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: haroo
      COUCHDB_PASSWORD: haroo

  spa:
    image: haroo-spa:latest
    depends_on:
      - couchdb
    ports:
      - 9000:80
  web:
    image: haroo-ssr:latest
    depends_on:
      - couchdb
    ports:
      - 9001:3000

volumes:
  couchdb: